### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nirkhut**
fixed typo

### CODE REVIEW

**Comment by andrelmfarias** [comment]
Hi @nirkhut,

Thanks for fixing this typo. I just realized that there is another typo in the same sentence. It should be: 
"The objective of `cdqa` converters **_is_** to make "
Can you please add it in you PR?
Also, you can PR directly to the Master branch. If everything is ok we will merge it.

**Comment by nirkhut** [comment]
@andrelmfarias 
Done.

**Comment by nirkhut** [comment]
@andrelmfarias 
sorry, I don't know what is PR, I'm new here... I just opened a new pull request, same as I did before. what is PR?

**Comment by andrelmfarias** [comment]
PR = pull request :)
You opened a PR to the add-unit-tests branch. 

I suggest you open a PR to the master branch ;)

**Comment by nirkhut** [comment]
lol ok, did it now.
Thank you for being nice!

**Pull request closed without merging**
